app/models.py
from flask_login import UserMixin

from app import db


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password = db.Column(db.String(128))
    name = db.Column(db.String(1000))

    def __repr__(self):
        return f"<User: {self.username}>"


class Track(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    quadrant = db.Column(db.Integer)
    title = db.Column(db.String(120))
    name = db.Column(db.String(1000))
    album = db.Column(db.String(128))
    lyrics = db.Column(db.String(100000000))

    def __repr__(self):
        return f"<Song: {self.title}"

app/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app():
    app = Flask(__name__)

    app.config["SECRET_KEY"] = "12FOEIGHEIOGIOOAIF"
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///db.sqlite"
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

    db.init_app(app)

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    from .models import User

    @login_manager.user_loader
    def load_user(user_id):
        # primary key
        return User.query.get(int(user_id))

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .views import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash

from app import db
from .models import User

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        remember = True if request.form.get("remember") else False

        user = User.query.filter_by(email=email).first()

        # user actually exists?
        if not user or not check_password_hash(user.password, password):
            flash("Please check your login details and try again.")
            return redirect(url_for("auth.login"))
        else:
            login_user(user, remember=remember)
            return redirect(url_for("main.clusters"))
    # if request.method == "GET":
    return render_template("login.html")


@auth.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        email = request.form.get("email")
        name = request.form.get("name")
        password = request.form.get("password")

        user = User.query.filter_by(email=email).first()  # if this returns a user then user exists

        if user:  # try again
            flash("Email address already exists")
            return redirect(url_for("auth.signup"))

        new_user = User(email=email, name=name, password=generate_password_hash(password,
                                                                                method="sha256"))

        db.session.add(new_user)
        db.session.commit()

        return redirect(url_for("auth.login"))
    return render_template("signup.html")


@auth.route("/signout")
@login_required
def signout():
    logout_user()
    return render_template("index.html")

app/views.py
from pathlib import Path

from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required

from app import db
from .model.inference import aggregate_inference
from .models import Track
from .spectrogram import create_mel_spectrogram

main = Blueprint("main", __name__)


@main.route("/")
def index():
    return render_template("index.html")


@main.route("/clusters")
@login_required
def clusters():
    list_q1 = Track.query.filter_by(quadrant=1)
    list_q2 = Track.query.filter_by(quadrant=2)
    list_q3 = Track.query.filter_by(quadrant=3)
    list_q4 = Track.query.filter_by(quadrant=4)

    return render_template("clusters.html", list_q1=list_q1, list_q2=list_q2,
                           list_q3=list_q3, list_q4=list_q4)


@main.route("/upload", methods=["GET", "POST"])
@login_required
def upload():
    if request.method == "POST":
        title = request.form.get("title")
        name = request.form.get("name")
        album = request.form.get("album")
        lyrics = request.form.get("lyrics")
        song_file = request.files["song"]

        song = Track.query.filter_by(title=title).first()
        artist = Track.query.filter_by(name=name).first()

        if song and artist:
            flash("Song by already exists")
            return redirect(url_for("main.upload"))

        # create spectrogram and get quadrant
        create_mel_spectrogram(song_file)
        spectrogram = Path("app/static/spectrogram/file.png")
        quadrant = aggregate_inference(spectrogram, lyrics)

        if quadrant:
            new_song = Track(quadrant=quadrant, title=title, name=name, album=album,
                             lyrics=lyrics)
            db.session.add(new_song)
            db.session.commit()
        else:
            flash("Failed to process cluster")
            return redirect(url_for("main.upload"))

        return redirect(url_for("main.clusters"))
    return render_template("upload.html")


@main.route("/track/<int:track_id>", methods=["GET"])
@login_required
def track(track_id):
    track = Track.query.filter_by(id=track_id).first()
    return render_template("track.html", track=track)

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Muse | {% block title %}{% endblock %} </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('main.index') }}" class="navbar-item">
                                Home
                            </a>
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('main.clusters') }}" class="navbar-item">
                                Clusters
                            </a>
                            <a href="{{ url_for('main.upload') }}" class="navbar-item">
                                Upload
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.signout') }}" class="navbar-item">
                                Logout
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

app/templates/clusters.html
{% extends "base.html" %}

{% block title %}Clusters{% endblock %}

{% block content %}
<table class="table hoverable is-fullwidth">
  <tr>
    <th colspan="3" scope="colgroup">Joyful Q1</th>
  </tr>
  <tr>
    <th>#</th>
    <th>Title</th>
    <th>Artist</th>
  </tr>
  <tr>
  {% for song in list_q1 %}
  <tr>
    <td>
      <a href="{{ url_for('main.track', track_id=song.id) }}">
        {{ song.id }}
      </a>
    </td>
    <td>{{ song.title }}</td>
    <td>{{ song.name }}</td>
  </tr>
  {% endfor %}
</table>

<table class="table hoverable is-fullwidth">
  <tr>
    <th colspan="3" scope="colgroup">Anger Q2</th>
  </tr>
  <tr>
    <th>#</th>
    <th>Title</th>
    <th>Artist</th>
  </tr>
  {% for song in list_q2 %}
  <tr>
    <td>
      <a href="{{ url_for('main.track', track_id=song.id) }}">
        {{ song.id }}
      </a>
    </td>
    <td>{{ song.title }}</td>
    <td>{{ song.name }}</td>
  </tr>
  {% endfor %}
</table>

<table class="table hoverable is-fullwidth">
  <tr>
    <th colspan="3" scope="colgroup">Sadness Q3</th>
  </tr>
  <tr>
    <th>#</th>
    <th>Title</th>
    <th>Artist</th>
  </tr>
  <tr>
  {% for song in list_q3 %}
  <tr>
    <td>
      <a href="{{ url_for('main.track', track_id=song.id) }}">
        {{ song.id }}
      </a>
    </td>
    <td>{{ song.title }}</td>
    <td>{{ song.name }}</td>
  </tr>
  {% endfor %}
</table>

<table class="table hoverable is-fullwidth">
  <tr>
    <th colspan="3" scope="colgroup">Tenderness Q4</th>
  </tr>
  <tr>
    <th>#</th>
    <th>Title</th>
    <th>Artist</th>
  </tr>
  <tr>
  {% for song in list_q4 %}
  <tr>
    <td>
      <a href="{{ url_for('main.track', track_id=song.id) }}">
        {{ song.id }}
      </a>
    </td>
    <td>{{ song.title }}</td>
    <td>{{ song.name }}</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
  <h1 class="title">Muse</h1>
  <div class="subtitle">
    Music playlist creator website for deploying MERA, a music clustering / classification algorithm based
    on mood / emotions people perceive in music.
  </div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="column is-4 is-offset-4">
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/playlist.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<table class="table hoverable is-fullwidth">
  <tr>
    <th colspan="3" scope="colgroup">Joyful Q1</th>
  </tr>
  <tr>
    <th>#</th>
    <th>Title</th>
    <th>Artist</th>
  </tr>
  <tr>
  {% for song in list_q1 %}
  <tr>
    <td>
      <a href="{{ url_for('main.track', track_id=song.id) }}">
        {{ song.id }}
      </a>
    </td>
    <td>{{ song.title }}</td>
    <td>{{ song.name }}</td>
  </tr>
  {% endfor %}
</table>

<table class="table hoverable is-fullwidth">
  <tr>
    <th colspan="3" scope="colgroup">Anger Q2</th>
  </tr>
  <tr>
    <th>#</th>
    <th>Title</th>
    <th>Artist</th>
  </tr>
  {% for song in list_q2 %}
  <tr>
    <td>
      <a href="{{ url_for('main.track', track_id=song.id) }}">
        {{ song.id }}
      </a>
    </td>
    <td>{{ song.title }}</td>
    <td>{{ song.name }}</td>
  </tr>
  {% endfor %}
</table>

<table class="table hoverable is-fullwidth">
  <tr>
    <th colspan="3" scope="colgroup">Sadness Q3</th>
  </tr>
  <tr>
    <th>#</th>
    <th>Title</th>
    <th>Artist</th>
  </tr>
  <tr>
  {% for song in list_q3 %}
  <tr>
    <td>
      <a href="{{ url_for('main.track', track_id=song.id) }}">
        {{ song.id }}
      </a>
    </td>
    <td>{{ song.title }}</td>
    <td>{{ song.name }}</td>
  </tr>
  {% endfor %}
</table>

<table class="table hoverable is-fullwidth">
  <tr>
    <th colspan="3" scope="colgroup">Tenderness Q4</th>
  </tr>
  <tr>
    <th>#</th>
    <th>Title</th>
    <th>Artist</th>
  </tr>
  <tr>
  {% for song in list_q4 %}
  <tr>
    <td>
      <a href="{{ url_for('main.track', track_id=song.id) }}">
        {{ song.id }}
      </a>
    </td>
    <td>{{ song.title }}</td>
    <td>{{ song.name }}</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<h1 class="title">
  Welcome, {{ name }}!
</h1>
{% endblock %}

app/templates/signup.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="column is-4 is-offset-4">
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">Login Page</a>
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/track.html
{% extends "base.html" %}

{% block title %}Track {{ track.id }}{% endblock %}

{% block content %}
<table class="table hoverable is-fullwidth">
  <tr>
    <th colspan="3" scope="colgroup">{{ track.id }}</th>
  </tr>
  <tr>
    <th>Thumbnail</th>
    <th>#</th>
    <th>Title</th>
    <th>Artist</th>
    <th>Lyrics</th>
  </tr>
  <tr>
  <tr>
    <td>
      <figure class="image is-128x128">
        <img src="https://bulma.io/images/placeholders/128x128.png">
      </figure>
    </td>
    <td>{{ track.id }}</td>
    <td>{{ track.title }}</td>
    <td>{{ track.name }}</td>
    <td>{{ track.lyrics }}</td>
  </tr>
</table>
{% endblock %}

app/templates/upload.html
{% extends "base.html" %}

{% block title %}Upload{% endblock %}

{% block content %}
<div class="column is-4 is-offset-4">
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/upload" enctype="multipart/form-data">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="title" placeholder="Song Title" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Artist Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="album" placeholder="Album Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="lyrics" placeholder="Lyrics" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="file" name="song" placeholder="Song File .MP3" autofocus="">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Upload</button>
        </form>
    </div>
</div>
{% endblock %}